version: "3.7"
name: "bofhers"

networks:
  proxy:
    external: true
  app:
    external: false

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-bofhers_php
      args:
        - PHP_VERSION=${BOFHERS_PHP_VERSION}
        - PHP_USER=${BOFHERS_PHP_USER}
        - PHP_UID=${BOFHERS_PHP_UID}
        - PHP_WORKDIR=${BOFHERS_APP_WORKDIR}
    image: bofhers_php
    container_name: bofhers_php
    env_file:
      - ../.env
      - ./.env
    stdin_open: true
    tty: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bofhers.rule=Host(`${COMPOSE_PROJECT_NAME}`)'
      - 'traefik.http.routers.bofhers.service=bofhers-service'
      - 'traefik.http.routers.bofhers.entrypoints=websecure'
      - 'traefik.http.routers.bofhers.tls=true'
      - 'traefik.http.services.bofhers-service.loadbalancer.server.port=${BOFHERS_LOCAL_BIND_PORT_CLIMODE}'
    volumes:
      - "..:${BOFHERS_APP_WORKDIR}"
    ports:
      - ${BOFHERS_LOCAL_BIND_PORT_CLIMODE}:${BOFHERS_LOCAL_BIND_PORT_CLIMODE}
    networks:
      - app
      - proxy
    depends_on:
      - database
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pmabofhers.rule=Host(`pma.${COMPOSE_PROJECT_NAME}`)'
      - 'traefik.http.routers.pmabofhers.service=pmabofhers-service'
      - 'traefik.http.routers.pmabofhers.entrypoints=websecure'
      - 'traefik.http.routers.pmabofhers.tls=true'
      - 'traefik.http.services.pmabofhers-service.loadbalancer.server.port=80'
    networks:
      - app
      - proxy
    depends_on:
      - database

